default:
	./run.sh pqxdh-model SecrecyInit SecrecyResp Authentication

confuseKemEc:
	./run.sh pqxdh-model ConfuseKemEc UnbreakableDH UnbreakableKEM DisableNoOPK

reach:
	./run.sh pqxdh-model Reach

reEncaps:
	./run.sh pqxdh-model ReEncaps UnbreakableDH UnbreakableKEM DisableNoOPK

clean:
	rm *.gen.pv -f 


