default:
	./run.sh pqxdh-model SecrecyInit SecrecyResp Authentication

confuseKemEc:
	./run.sh pqxdh-model ConfuseKemEc UnbreakableDH UnbreakableKEM DisableNoOPK

reach:
	./run.sh pqxdh-model Reach

reEncaps:
	./run.sh pqxdh-model ReEncaps UnbreakableDH UnbreakableKEM DisableNoOPK



pkkem-in-ad:
	./run.sh pqxdh-PQKEM-in-AD SecrecyInit SecrecyResp Authentication


pkkem-in-ad-reach:
	./run.sh pqxdh-PQKEM-in-AD Reach

pkkem-in-kdf:
	./run.sh pqxdh-PQKEM-in-KDF SecrecyInit SecrecyResp Authentication


pkkem-in-kdf-reach:
	./run.sh pqxdh-PQKEM-in-KDF Reach



clean:
	rm *.gen.pv -f 


